#!/bin/bash

# Función para asignar usuarios a grupos
assign_users_to_groups() {
    local total_usuarios=45
    local total_grupos=31
    local usuarios_por_grupo=3

    for ((grupo_num = 1; grupo_num <= total_grupos; grupo_num++))
    do
        local user_num=$((grupo_num * usuarios_por_grupo - usuarios_por_grupo + 1))
        local grupo="grupos$grupo_num"  # Modificado a "grupos"

        # Verifica si el grupo existe
        if ! getent group "$grupo" &>/dev/null; then
            echo "El grupo $grupo no existe."
            continue
        fi

        for ((i = 0; i < usuarios_por_grupo; i++))
        do
            local usuario="usuario$user_num"

            # Verifica si el usuario existe
            if id "$usuario" &>/dev/null; then
                sudo usermod -aG "$grupo" "$usuario"
                echo "Usuario $usuario asignado al grupo $grupo"
            else
                echo "El usuario $usuario no existe."
            fi

            ((user_num++))
        done
    done
}

# Llama a la función para asignar usuarios a grupos
assign_users_to_groups
